/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PKG_Frame;

import DIP.EnhanceBrightness;	
import DIP.OpenFile;
import DIP.EnhanceContrast;
import DIP.EnhanceSharpeness;
import DIP.Flip;
import DIP.GaussianFilter;
import DIP.GreyScale;
import DIP.N_NiveauDeGris;
import DIP.Zoom;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.opencv.core.Core;

public class HomeFrame extends javax.swing.JFrame {

    CardLayout c;
    public static File file;
    public static BufferedImage image;

    public static File editedFile;

    private void exportFile(BufferedImage img) {
        try {
            ImageIO.write(img, "jpg", editedFile);
        } catch (IOException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        super("Démonstration DIP");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initComponents();
        getContentPane().setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        SideBar = new javax.swing.JPanel();
        btnSrcImg = new javax.swing.JButton();
        btnGrayScale = new javax.swing.JButton();
        btnGrayScale1 = new javax.swing.JButton();
        btnContrast = new javax.swing.JButton();
        btnSharpness = new javax.swing.JButton();
        btnBrightness = new javax.swing.JButton();
        btnGaussianFilter = new javax.swing.JButton();
        btnZoom = new javax.swing.JButton();
        btnZoom1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        FileTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SideBar.setBackground(new java.awt.Color(204, 204, 204));

        btnSrcImg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSrcImg.setText("Source Image");
        btnSrcImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrcImgActionPerformed(evt);
            }
        });

        btnGrayScale.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnGrayScale.setText("GrayScale");
        btnGrayScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrayScaleActionPerformed(evt);
            }
        });

        btnGrayScale1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnGrayScale1.setText("Gray Levels");
        btnGrayScale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrayScale1ActionPerformed(evt);
            }
        });

        btnContrast.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnContrast.setText("Contrast");
        btnContrast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContrastActionPerformed(evt);
            }
        });

        btnSharpness.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSharpness.setText("Sharpness");
        btnSharpness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSharpnessActionPerformed(evt);
            }
        });

        btnBrightness.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBrightness.setText("Brightness");
        btnBrightness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrightnessActionPerformed(evt);
            }
        });

        btnGaussianFilter.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnGaussianFilter.setText("Gaussian Filter");
        btnGaussianFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaussianFilterActionPerformed(evt);
            }
        });

        btnZoom.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnZoom.setText("Zoom");
        btnZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoomActionPerformed(evt);
            }
        });

        btnZoom1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnZoom1.setText("Flip Image");
        btnZoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZoom1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGrayScale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSrcImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrayScale1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContrast, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSharpness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBrightness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGaussianFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnZoom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnSrcImg)
                .addGap(27, 27, 27)
                .addComponent(btnGrayScale)
                .addGap(25, 25, 25)
                .addComponent(btnGrayScale1)
                .addGap(25, 25, 25)
                .addComponent(btnContrast)
                .addGap(18, 18, 18)
                .addComponent(btnSharpness)
                .addGap(18, 18, 18)
                .addComponent(btnBrightness)
                .addGap(18, 18, 18)
                .addComponent(btnGaussianFilter)
                .addGap(18, 18, 18)
                .addComponent(btnZoom)
                .addGap(18, 18, 18)
                .addComponent(btnZoom1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ImageLabel.setText(".");
        ImageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Get Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        FileTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        FileTextField.setText("select a file...");
        FileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(FileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSrcImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrcImgActionPerformed
        try {
            image = ImageIO.read(file);
            displayImage(image);
            exportFile(image);

        } catch (IOException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSrcImgActionPerformed


    private void btnGrayScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrayScaleActionPerformed
        image = GreyScale.getGreyScale(image);
        displayImage(image);
        exportFile(image);
    }//GEN-LAST:event_btnGrayScaleActionPerformed
    private void displayImage(BufferedImage image) {
        ImageIcon icon = new ImageIcon(image);
        ImageLabel.setIcon(icon);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OpenFile of = new OpenFile();
        try {
            of.PickMe();
            FileTextField.setText(of.file.getAbsolutePath());
            file = of.file;
            image = of.image;
            System.out.println(file.getParent());
            editedFile = new File(file.getParent() + "\\res.jpg");
            exportFile(image);
            displayImage(image);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void FileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileTextFieldActionPerformed

    }//GEN-LAST:event_FileTextFieldActionPerformed

    private void btnGrayScale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrayScale1ActionPerformed
        // TODO add your handling code here:
        String in = JOptionPane.showInputDialog("Nombre de niveaux de gris ? ");
        int nbr = Integer.parseInt(in);
        image = N_NiveauDeGris.getNNiveau(image, nbr);
        displayImage(image);
        exportFile(image);

    }//GEN-LAST:event_btnGrayScale1ActionPerformed

    private void btnContrastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContrastActionPerformed
        image = EnhanceContrast.getContrasted(editedFile.getAbsolutePath());
        displayImage(image);
        exportFile(image);
    }//GEN-LAST:event_btnContrastActionPerformed

    private void btnSharpnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSharpnessActionPerformed
        // TODO add your handling code here:
        image = EnhanceSharpeness.getSharpened(editedFile.getAbsolutePath());
        displayImage(image);
        exportFile(image);
    }//GEN-LAST:event_btnSharpnessActionPerformed

    private void btnBrightnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrightnessActionPerformed
        // TODO add your handling code here:
        String in = JOptionPane.showInputDialog("Alpha = ");
        double alpha = Double.parseDouble(in);
        in = JOptionPane.showInputDialog("Beta = ");
        double beta = Double.parseDouble(in);
        image = EnhanceBrightness.getBrighter(editedFile.getAbsolutePath(), alpha, beta);
        displayImage(image);
        exportFile(image);
    }//GEN-LAST:event_btnBrightnessActionPerformed

    private void btnGaussianFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaussianFilterActionPerformed
        // TODO add your handling code here:
        String in = JOptionPane.showInputDialog("Amount = ? ");

        int amount = Integer.parseInt(in);

        image = GaussianFilter.gaussianBlur(editedFile.getAbsolutePath(), amount);

        displayImage(image);
        exportFile(image);
    }//GEN-LAST:event_btnGaussianFilterActionPerformed

    private void btnZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomActionPerformed
        // TODO add your handling code here:
        String in = JOptionPane.showInputDialog("Zoom x = ? ");

        double zoomFactor = Double.parseDouble(in);
        image = Zoom.getZoomed(editedFile.getAbsolutePath(), zoomFactor);

        displayImage(image);
        exportFile(image);
    }//GEN-LAST:event_btnZoomActionPerformed

    private void btnZoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoom1ActionPerformed
        // TODO add your handling code here:
        image = Flip.getFlipped(image);
        displayImage(image);
        exportFile(image);

    }//GEN-LAST:event_btnZoom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FileTextField;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel SideBar;
    private javax.swing.JButton btnBrightness;
    private javax.swing.JButton btnContrast;
    private javax.swing.JButton btnGaussianFilter;
    private javax.swing.JButton btnGrayScale;
    private javax.swing.JButton btnGrayScale1;
    private javax.swing.JButton btnSharpness;
    private javax.swing.JButton btnSrcImg;
    private javax.swing.JButton btnZoom;
    private javax.swing.JButton btnZoom1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
